# -*- coding: utf-8 -*-
"""oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gn6VzJVLF03_8BfpRNrrYh897wufjiZ_
"""

class Student:
    def __init__(self, name, subjects):
        self.name = name
        self.subjects = subjects
        self.marks = []

    def enter_marks(self):
        print("Enter marks for", self.name)
        for i in range(self.subjects):
            mark = float(input(f"Enter marks for subject {i+1}: "))
            self.marks.append(mark)

    def calculate_cgpa(self):
        total = sum(self.marks)
        average = total / self.subjects
        cgpa = average / 10
        return cgpa

    def display(self):
        cgpa = self.calculate_cgpa()
        print("\nStudent Name:", self.name)
        print("Marks:", self.marks)
        print("CGPA:", round(cgpa, 2))


name = input("Enter student name: ")
subjects = int(input("Enter number of subjects: "))

s1 = Student(name, subjects)
s1.enter_marks()
s1.display()

from google.colab import drive
drive.mount('/content/drive')

class PasswordManager:
    def __init__(self):
        self.passwords = {}

    def add_password(self, site, password):
        self.passwords[site] = password

    def get_password(self, site):
        print("Password:", self.passwords.get(site, "Not found"))


pm = PasswordManager()
pm.add_password("gmail", "")
pm.get_password("gmail")

class Freelancer:
    def __init__(self, name, skill):
        self.name = name
        self.skill = skill

class Project:
    def __init__(self, title):
        self.title = title

    def assign(self, freelancer):
        print(f"{freelancer.name} assigned to {self.title}")


f1 = Freelancer("Sita", "Python")
p1 = Project("Website")
p1.assign(f1)

class Product:
    def __init__(self, name, quantity):
        self.name = name
        self.quantity = quantity


class Warehouse:
    def __init__(self):
        self.inventory = {}


    def add_product(self, name, qty):
        if name in self.inventory:
            self.inventory[name].quantity += qty
        else:
            self.inventory[name] = Product(name, qty)
        print(qty, name, "added to warehouse")


    def remove_product(self, name, qty):
        if name in self.inventory and self.inventory[name].quantity >= qty:
            self.inventory[name].quantity -= qty
            print(qty, name, "removed from warehouse")
        else:
            print("Not enough stock")


    def generate_report(self):
        print("\nInventory Report")
        for product in self.inventory.values():
            print(product.name, ":", product.quantity)


    def forecast_demand(self):
        print("\nDemand Forecast")
        for product in self.inventory.values():
            forecast = product.quantity + 10
            print("Expected demand for", product.name, "=", forecast)


w = Warehouse()

w.add_product("Laptop", 20)
w.add_product("Mouse", 50)

w.remove_product("Laptop", 5)

w.generate_report()

w.forecast_demand()